// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnhucR1bq7A4Xv5TokqlWIQpo49zG7q7c',
    appId: '1:857860432080:web:76211650ba5c6770223ed5',
    messagingSenderId: '857860432080',
    projectId: 'hfa---health-for-all',
    authDomain: 'hfa---health-for-all.firebaseapp.com',
    storageBucket: 'hfa---health-for-all.appspot.com',
    measurementId: 'G-QJVRSV9GGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4Vivi4Zrz7el0bWyWQ4OJd0Qfai4evM',
    appId: '1:857860432080:android:c991295f2a0e2558223ed5',
    messagingSenderId: '857860432080',
    projectId: 'hfa---health-for-all',
    storageBucket: 'hfa---health-for-all.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKMI_V2b3Fl3nQHgwL-OfGVSg0KF4jzw',
    appId: '1:857860432080:ios:e07ef35a7e3bfad8223ed5',
    messagingSenderId: '857860432080',
    projectId: 'hfa---health-for-all',
    storageBucket: 'hfa---health-for-all.appspot.com',
    iosClientId: '857860432080-og4mh520u6qis8ta92opgfcgfahr8gru.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthForAll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhKMI_V2b3Fl3nQHgwL-OfGVSg0KF4jzw',
    appId: '1:857860432080:ios:e07ef35a7e3bfad8223ed5',
    messagingSenderId: '857860432080',
    projectId: 'hfa---health-for-all',
    storageBucket: 'hfa---health-for-all.appspot.com',
    iosClientId: '857860432080-og4mh520u6qis8ta92opgfcgfahr8gru.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthForAll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnhucR1bq7A4Xv5TokqlWIQpo49zG7q7c',
    appId: '1:857860432080:web:3ea755b32d069d9c223ed5',
    messagingSenderId: '857860432080',
    projectId: 'hfa---health-for-all',
    authDomain: 'hfa---health-for-all.firebaseapp.com',
    storageBucket: 'hfa---health-for-all.appspot.com',
    measurementId: 'G-ZH28C3YR62',
  );
}
